//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jens_EFVenner
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MainVenneTabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainVenneTabel()
        {
            this.Alders = new ObservableCollection<Alder>();
            this.Favoritspils = new ObservableCollection<Favoritspil>();
            this.Hjemmesides = new ObservableCollection<Hjemmeside>();
            this.KaldeNavns = new ObservableCollection<KaldeNavn>();
            this.MailAdrs = new ObservableCollection<MailAdr>();
            this.TelefonNrs = new ObservableCollection<TelefonNr>();
        }
    
        public int id { get; set; }
        public string fornavn { get; set; }
        public string efternavn { get; set; }
        public string adresse { get; set; }
        public int postNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Alder> Alders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Favoritspil> Favoritspils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Hjemmeside> Hjemmesides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<KaldeNavn> KaldeNavns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<MailAdr> MailAdrs { get; set; }
        public virtual PostByTabel PostByTabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TelefonNr> TelefonNrs { get; set; }
    }
}
