//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jens_EFVenner
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PostByTabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostByTabel()
        {
            this.MainVenneTabels = new ObservableCollection<MainVenneTabel>();
        }
    
        public int postNr { get; set; }
        public string byNavn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<MainVenneTabel> MainVenneTabels { get; set; }
    }
}
