//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFVenner
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainVenneTabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainVenneTabel()
        {
            this.Alders = new HashSet<Alder>();
            this.Favoritspils = new HashSet<Favoritspil>();
            this.Hjemmesides = new HashSet<Hjemmeside>();
            this.KaldeNavns = new HashSet<KaldeNavn>();
            this.MailAdrs = new HashSet<MailAdr>();
            this.TelefonNrs = new HashSet<TelefonNr>();
        }
    
        public int id { get; set; }
        public string fornavn { get; set; }
        public string efternavn { get; set; }
        public string adresse { get; set; }
        public int postNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alder> Alders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoritspil> Favoritspils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hjemmeside> Hjemmesides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KaldeNavn> KaldeNavns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailAdr> MailAdrs { get; set; }
        public virtual PostByTabel PostByTabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelefonNr> TelefonNrs { get; set; }
    }
}
