//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brandt_EFVenner
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MainVenneTabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainVenneTabel()
        {
            this.Alder = new ObservableCollection<Alder>();
            this.Favoritspil = new ObservableCollection<Favoritspil>();
            this.Hjemmeside = new ObservableCollection<Hjemmeside>();
            this.KaldeNavn = new ObservableCollection<KaldeNavn>();
            this.MailAdr = new ObservableCollection<MailAdr>();
            this.TelefonNr = new ObservableCollection<TelefonNr>();
        }
    
        public int id { get; set; }
        public string fornavn { get; set; }
        public string efternavn { get; set; }
        public string adresse { get; set; }
        public int postNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Alder> Alder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Favoritspil> Favoritspil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Hjemmeside> Hjemmeside { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<KaldeNavn> KaldeNavn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<MailAdr> MailAdr { get; set; }
        public virtual PostByTabel PostByTabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TelefonNr> TelefonNr { get; set; }
    }
}
