//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brandt_EFVenner
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TelefonType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelefonType()
        {
            this.TelefonNr = new ObservableCollection<TelefonNr>();
        }
    
        public int id { get; set; }
        public string telefonType1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TelefonNr> TelefonNr { get; set; }
    }
}
