//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brandt_EFVenner
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TelefonNr
    {
        public int id { get; set; }
        public int venId { get; set; }
        public string telefonNr1 { get; set; }
        public int type { get; set; }
    
        public virtual MainVenneTabel MainVenneTabel { get; set; }
        public virtual TelefonType TelefonType { get; set; }
    }
}
