//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brandt_EFVenner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VennerEntities : DbContext
    {
        public VennerEntities()
            : base("name=VennerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alder> Alder { get; set; }
        public virtual DbSet<Favoritspil> Favoritspil { get; set; }
        public virtual DbSet<Hjemmeside> Hjemmeside { get; set; }
        public virtual DbSet<KaldeNavn> KaldeNavn { get; set; }
        public virtual DbSet<KaldenavnType> KaldenavnType { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<MailAdr> MailAdr { get; set; }
        public virtual DbSet<MailType> MailType { get; set; }
        public virtual DbSet<MainVenneTabel> MainVenneTabel { get; set; }
        public virtual DbSet<PostByTabel> PostByTabel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TelefonNr> TelefonNr { get; set; }
        public virtual DbSet<TelefonType> TelefonType { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
    }
}
